services:
  db:
    image: postgres:16-alpine
    container_name: bitsieve-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bitsieve
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: ./PrimeCalcServer
    container_name: bitsieve-server
    ports:
      - "1337:1337"
    depends_on:
      - db
    environment:
      - DB_URL=jdbc:postgresql://db:5432/bitsieve

volumes:
  postgres_data:
